### ISSUE TITLE
Steemit Icon for social link menu

### ISSUE THREAD

**Issue by sodom89** [ThemeZee/admiral#1]
Please, can you add the [Steemit Icon](https://en.wikipedia.org/wiki/File:Steemit_Logo.svg) to the social link menu or tell me how to do this myself?

**Comment by Netzberufler** [comment]
The social icons menu works with the Genericons icon font, which does not support a Steemit Icon. Right now it is not possible to extend it with additional icons, you have to recreate your own social icons menu to achieve that. I'm sorry.
